import { computed, ref } from 'vue'

export type Locale = 'en' | 'sk' | 'hu'

const STORAGE_KEY = 'vehicle-garage:locale'
const locale = ref<Locale>(readLocale())
if (typeof document !== 'undefined') document.documentElement.lang = locale.value

const messages: Record<Locale, Record<string, string>> = {
	en: {
		'brand.name': 'Vehicle Garage', 'nav.main': 'Main navigation', 'nav.garage': 'Garage', 'nav.obd': 'OBD', 'nav.manual': 'Civic manual', 'nav.local': 'Local garage', 'nav.saved': 'Saved on this device', 'nav.profile': 'Open profile', 'top.eyebrow': 'PERSONAL OWNERSHIP JOURNAL', 'top.title': 'Keep your garage in order.', 'language.label': 'Language',
		'home.eyebrow': 'VEHICLE GARAGE', 'home.title': 'Keep every vehicle story close.', 'home.description': 'Track ownership, understand service history, and reach the right manual without losing context.', 'home.open': 'Open garage', 'home.manual': 'Browse Civic manual',
		'garage.eyebrow': 'YOUR COLLECTION', 'garage.title': 'Garage', 'garage.description': 'Every vehicle, service, and story in one calm workspace.', 'garage.export': 'Export backup', 'garage.import': 'Import backup', 'garage.add': 'Add vehicle', 'garage.vehicles': 'Vehicles', 'garage.inGarage': 'in your garage', 'garage.cost': 'Total ownership cost', 'garage.across': 'across all vehicles', 'garage.mileage': 'Combined mileage', 'garage.count': 'entries', 'garage.collection': 'COLLECTION', 'garage.yourVehicles': 'Your vehicles', 'garage.odometer': 'ODOMETER', 'garage.ownershipCost': 'OWNERSHIP COST', 'garage.openVehicle': 'Open vehicle', 'garage.exported': 'Backup exported', 'garage.imported': 'Backup imported',
		'form.eyebrow': 'YOUR COLLECTION', 'form.title': 'Add vehicle', 'form.description': 'Keep the details of your vehicle in one place.', 'form.manufacturer': 'Manufacturer', 'form.model': 'Model', 'form.year': 'Production year', 'form.body': 'Body style / generation', 'form.engine': 'Engine', 'form.fuel': 'Fuel type', 'form.odometer': 'Odometer (km)', 'form.color': 'Color', 'form.cost': 'Ownership cost', 'form.catalogData': 'CATALOG DATA', 'form.localData': 'LOCAL DATA', 'form.verify': 'Verify technical data', 'form.addDetails': 'Add engine details', 'form.editable': 'Editable locally', 'form.engineCode': 'Engine code', 'form.displacement': 'Displacement (cc)', 'form.cylinders': 'Cylinders', 'form.power': 'Power (HP)', 'form.torque': 'Torque (Nm)', 'form.economy': 'Combined fuel use (L/100 km)', 'form.transmission': 'Transmission', 'form.drivetrain': 'Drivetrain', 'form.crossBody': 'Search engines across all body styles', 'form.crossBodyWarning': 'Engine found in {generation}. Confirm body style before saving.', 'form.customEngine': 'I cannot find my engine', 'form.cancel': 'Cancel', 'form.submit': 'Add vehicle', 'form.invalidCatalog': 'Select a vehicle from the catalog before adding it', 'form.catalogUnavailable': 'Vehicle catalog unavailable. Retry.', 'form.retryLater': 'Retry or continue later.', 'form.engineCodeHint': 'e.g. D16V1',
		'vehicle.back': 'Back to garage', 'vehicle.overview': 'VEHICLE OVERVIEW', 'vehicle.manual': "Owner's manual", 'vehicle.edit': 'Edit vehicle', 'vehicle.cancelEdit': 'Cancel editing', 'vehicle.profile': 'VEHICLE PROFILE', 'vehicle.editProfile': 'Edit profile', 'vehicle.save': 'Save changes', 'vehicle.cancel': 'Cancel', 'vehicle.make': 'Make', 'vehicle.model': 'Model', 'vehicle.year': 'Year', 'vehicle.engine': 'Engine', 'vehicle.fuel': 'Fuel type', 'vehicle.odometer': 'Odometer', 'vehicle.color': 'Color', 'vehicle.ownershipCost': 'Ownership cost', 'vehicle.currentOdometer': 'CURRENT ODOMETER', 'vehicle.ownedSince': 'Owned since 2021', 'vehicle.totalCost': 'TOTAL COST', 'vehicle.sincePurchase': 'since purchase', 'vehicle.avgFuel': 'AVG. FUEL', 'vehicle.lastYear': 'last 12 months', 'vehicle.lastService': 'LAST SERVICE', 'vehicle.oil': 'Oil + filter change', 'vehicle.selectedSpec': 'SELECTED SPECIFICATION', 'vehicle.technical': 'Technical data', 'vehicle.engineCode': 'Engine code', 'vehicle.displacement': 'Displacement', 'vehicle.cylinders': 'Cylinders', 'vehicle.power': 'Power', 'vehicle.torque': 'Torque', 'vehicle.transmission': 'Transmission', 'vehicle.drivetrain': 'Drivetrain', 'vehicle.economy': 'Combined fuel use', 'vehicle.history': 'SERVICE HISTORY', 'vehicle.activity': 'Recent activity', 'vehicle.addRecord': 'Add record', 'vehicle.records': 'Maintenance records', 'vehicle.notFound': 'Vehicle not found', 'vehicle.return': 'Return to garage', 'maintenance.date': 'Date', 'maintenance.odometer': 'Odometer', 'maintenance.description': 'Work performed', 'maintenance.category': 'Category', 'maintenance.cost': 'Cost', 'maintenance.performedBy': 'Performed by', 'maintenance.owner': 'Owner', 'maintenance.workshop': 'Workshop', 'maintenance.save': 'Save record',
	},
	sk: {
		'brand.name': 'Garáž vozidiel', 'nav.main': 'Hlavná navigácia', 'nav.garage': 'Garáž', 'nav.obd': 'OBD', 'nav.manual': 'Manuál Civic', 'nav.local': 'Lokálna garáž', 'nav.saved': 'Uložené v tomto zariadení', 'nav.profile': 'Otvoriť profil', 'top.eyebrow': 'OSOBNÝ DENNÍK VLASTNÍCTVA', 'top.title': 'Majte svoju garáž v poriadku.', 'language.label': 'Jazyk',
		'home.eyebrow': 'GARÁŽ VOZIDIEL', 'home.title': 'Majte príbeh každého vozidla vždy pri sebe.', 'home.description': 'Sledujte vlastníctvo, servisnú históriu a správny manuál bez straty súvislostí.', 'home.open': 'Otvoriť garáž', 'home.manual': 'Prehliadať manuál Civic',
		'garage.eyebrow': 'VAŠA ZBIERKA', 'garage.title': 'Garáž', 'garage.description': 'Vozidlá, servis a ich história na jednom mieste.', 'garage.export': 'Exportovať zálohu', 'garage.import': 'Importovať zálohu', 'garage.add': 'Pridať vozidlo', 'garage.vehicles': 'Vozidlá', 'garage.inGarage': 'vo vašej garáži', 'garage.cost': 'Celkové náklady na vlastníctvo', 'garage.across': 'za všetky vozidlá', 'garage.mileage': 'Celkový nájazd', 'garage.count': 'záznamov', 'garage.collection': 'ZBIERKA', 'garage.yourVehicles': 'Vaše vozidlá', 'garage.odometer': 'NÁJAZD', 'garage.ownershipCost': 'NÁKLADY', 'garage.openVehicle': 'Otvoriť vozidlo', 'garage.exported': 'Záloha exportovaná', 'garage.imported': 'Záloha importovaná',
		'form.eyebrow': 'VAŠA ZBIERKA', 'form.title': 'Pridať vozidlo', 'form.description': 'Majte údaje o vozidle na jednom mieste.', 'form.manufacturer': 'Výrobca', 'form.model': 'Model', 'form.year': 'Rok výroby', 'form.body': 'Karoséria / generácia', 'form.engine': 'Motor', 'form.fuel': 'Typ paliva', 'form.odometer': 'Nájazd (km)', 'form.color': 'Farba', 'form.cost': 'Náklady na vlastníctvo', 'form.catalogData': 'ÚDAJE Z KATALÓGU', 'form.localData': 'LOKÁLNE ÚDAJE', 'form.verify': 'Overte technické údaje', 'form.addDetails': 'Pridajte údaje o motore', 'form.editable': 'Upraviteľné lokálne', 'form.engineCode': 'Kód motora', 'form.displacement': 'Zdvihový objem (cm³)', 'form.cylinders': 'Valce', 'form.power': 'Výkon (HP)', 'form.torque': 'Krútiaci moment (Nm)', 'form.economy': 'Kombinovaná spotreba (l/100 km)', 'form.transmission': 'Prevodovka', 'form.drivetrain': 'Pohon', 'form.crossBody': 'Hľadať motory vo všetkých karosériách', 'form.crossBodyWarning': 'Motor nájdený v generácii {generation}. Pred uložením overte karosériu.', 'form.customEngine': 'Motor nemôžem nájsť', 'form.cancel': 'Zrušiť', 'form.submit': 'Pridať vozidlo', 'form.invalidCatalog': 'Pred pridaním vyberte vozidlo z katalógu', 'form.catalogUnavailable': 'Katalóg vozidiel nie je dostupný. Skúste znova.', 'form.retryLater': 'Skúste znova alebo pokračujte neskôr.', 'form.engineCodeHint': 'napr. D16V1',
		'vehicle.back': 'Späť do garáže', 'vehicle.overview': 'PREHĽAD VOZIDLA', 'vehicle.manual': 'Manuál vozidla', 'vehicle.edit': 'Upraviť vozidlo', 'vehicle.cancelEdit': 'Zrušiť úpravy', 'vehicle.profile': 'PROFIL VOZIDLA', 'vehicle.editProfile': 'Upraviť profil', 'vehicle.save': 'Uložiť zmeny', 'vehicle.cancel': 'Zrušiť', 'vehicle.make': 'Výrobca', 'vehicle.model': 'Model', 'vehicle.year': 'Rok', 'vehicle.engine': 'Motor', 'vehicle.fuel': 'Typ paliva', 'vehicle.odometer': 'Nájazd', 'vehicle.color': 'Farba', 'vehicle.ownershipCost': 'Náklady na vlastníctvo', 'vehicle.currentOdometer': 'AKTUÁLNY NÁJAZD', 'vehicle.ownedSince': 'Vlastnené od roku 2021', 'vehicle.totalCost': 'CELKOVÉ NÁKLADY', 'vehicle.sincePurchase': 'od kúpy', 'vehicle.avgFuel': 'PRIEMERNÁ SPOTREBA', 'vehicle.lastYear': 'za posledných 12 mesiacov', 'vehicle.lastService': 'POSLEDNÝ SERVIS', 'vehicle.oil': 'Olej a filter', 'vehicle.selectedSpec': 'VYBRANÁ ŠPECIFIKÁCIA', 'vehicle.technical': 'Technické údaje', 'vehicle.engineCode': 'Kód motora', 'vehicle.displacement': 'Zdvihový objem', 'vehicle.cylinders': 'Valce', 'vehicle.power': 'Výkon', 'vehicle.torque': 'Krútiaci moment', 'vehicle.transmission': 'Prevodovka', 'vehicle.drivetrain': 'Pohon', 'vehicle.economy': 'Kombinovaná spotreba', 'vehicle.history': 'SERVISNÁ HISTÓRIA', 'vehicle.activity': 'Nedávna aktivita', 'vehicle.addRecord': 'Pridať záznam', 'vehicle.records': 'Servisné záznamy', 'vehicle.notFound': 'Vozidlo sa nenašlo', 'vehicle.return': 'Späť do garáže', 'maintenance.date': 'Dátum', 'maintenance.odometer': 'Nájazd', 'maintenance.description': 'Vykonaná práca', 'maintenance.category': 'Kategória', 'maintenance.cost': 'Náklady', 'maintenance.performedBy': 'Vykonal', 'maintenance.owner': 'Majiteľ', 'maintenance.workshop': 'Servis', 'maintenance.save': 'Uložiť záznam',
	},
	hu: {
		'brand.name': 'Járműgarázs', 'nav.main': 'Fő navigáció', 'nav.garage': 'Garázs', 'nav.obd': 'OBD', 'nav.manual': 'Civic kézikönyv', 'nav.local': 'Helyi garázs', 'nav.saved': 'Ezen az eszközön mentve', 'nav.profile': 'Profil megnyitása', 'top.eyebrow': 'SZEMÉLYES TULAJDONOSI NAPLÓ', 'top.title': 'Tartsd rendben a garázsod.', 'language.label': 'Nyelv',
		'home.eyebrow': 'JÁRMŰGARÁZS', 'home.title': 'Minden jármű története legyen kéznél.', 'home.description': 'Kövesd a tulajdonlást, értsd a szervizelőzményeket, és találd meg a megfelelő kézikönyvet.', 'home.open': 'Garázs megnyitása', 'home.manual': 'Civic kézikönyv böngészése',
		'garage.eyebrow': 'GYŰJTEMÉNYED', 'garage.title': 'Garázs', 'garage.description': 'Járművek, szerviz és történet egy nyugodt munkaterületen.', 'garage.export': 'Biztonsági mentés exportálása', 'garage.import': 'Biztonsági mentés importálása', 'garage.add': 'Jármű hozzáadása', 'garage.vehicles': 'Járművek', 'garage.inGarage': 'a garázsodban', 'garage.cost': 'Teljes tulajdonlási költség', 'garage.across': 'minden járműre', 'garage.mileage': 'Összes futásteljesítmény', 'garage.count': 'bejegyzés', 'garage.collection': 'GYŰJTEMÉNY', 'garage.yourVehicles': 'Járműveid', 'garage.odometer': 'FUTÁSTELJESÍTMÉNY', 'garage.ownershipCost': 'TULAJDONLÁSI KÖLTSÉG', 'garage.openVehicle': 'Jármű megnyitása', 'garage.exported': 'Biztonsági mentés exportálva', 'garage.imported': 'Biztonsági mentés importálva',
		'form.eyebrow': 'GYŰJTEMÉNYED', 'form.title': 'Jármű hozzáadása', 'form.description': 'Tartsd a jármű adatait egy helyen.', 'form.manufacturer': 'Gyártó', 'form.model': 'Modell', 'form.year': 'Gyártási év', 'form.body': 'Karosszéria / generáció', 'form.engine': 'Motor', 'form.fuel': 'Üzemanyag típusa', 'form.odometer': 'Futásteljesítmény (km)', 'form.color': 'Szín', 'form.cost': 'Tulajdonlási költség', 'form.catalogData': 'KATALÓGUSADATOK', 'form.localData': 'HELYI ADATOK', 'form.verify': 'Műszaki adatok ellenőrzése', 'form.addDetails': 'Motoradatok hozzáadása', 'form.editable': 'Helyben szerkeszthető', 'form.engineCode': 'Motorkód', 'form.displacement': 'Hengerűrtartalom (cm³)', 'form.cylinders': 'Hengerek', 'form.power': 'Teljesítmény (LE)', 'form.torque': 'Nyomaték (Nm)', 'form.economy': 'Kombinált fogyasztás (l/100 km)', 'form.transmission': 'Sebességváltó', 'form.drivetrain': 'Hajtás', 'form.crossBody': 'Motorok keresése minden karosszériában', 'form.crossBodyWarning': 'A motor ebben a generációban található: {generation}. Mentés előtt ellenőrizd a karosszériát.', 'form.customEngine': 'Nem találom a motoromat', 'form.cancel': 'Mégse', 'form.submit': 'Jármű hozzáadása', 'form.invalidCatalog': 'Hozzáadás előtt válassz járművet a katalógusból', 'form.catalogUnavailable': 'A járműkatalógus nem érhető el. Próbáld újra.', 'form.retryLater': 'Próbáld újra, vagy folytasd később.', 'form.engineCodeHint': 'pl. D16V1',
		'vehicle.back': 'Vissza a garázshoz', 'vehicle.overview': 'JÁRMŰ ÁTTEKINTÉS', 'vehicle.manual': 'Használati kézikönyv', 'vehicle.edit': 'Jármű szerkesztése', 'vehicle.cancelEdit': 'Szerkesztés megszakítása', 'vehicle.profile': 'JÁRMŰPROFIL', 'vehicle.editProfile': 'Profil szerkesztése', 'vehicle.save': 'Módosítások mentése', 'vehicle.cancel': 'Mégse', 'vehicle.make': 'Gyártó', 'vehicle.model': 'Modell', 'vehicle.year': 'Év', 'vehicle.engine': 'Motor', 'vehicle.fuel': 'Üzemanyag', 'vehicle.odometer': 'Futásteljesítmény', 'vehicle.color': 'Szín', 'vehicle.ownershipCost': 'Tulajdonlási költség', 'vehicle.currentOdometer': 'AKTUÁLIS FUTÁSTELJESÍTMÉNY', 'vehicle.ownedSince': 'Tulajdonban 2021 óta', 'vehicle.totalCost': 'TELJES KÖLTSÉG', 'vehicle.sincePurchase': 'vásárlás óta', 'vehicle.avgFuel': 'ÁTLAGFOGYASZTÁS', 'vehicle.lastYear': 'az elmúlt 12 hónapban', 'vehicle.lastService': 'UTOLSÓ SZERVIZ', 'vehicle.oil': 'Olaj és szűrőcsere', 'vehicle.selectedSpec': 'KIVÁLASZTOTT SPECIFIKÁCIÓ', 'vehicle.technical': 'Műszaki adatok', 'vehicle.engineCode': 'Motorkód', 'vehicle.displacement': 'Hengerűrtartalom', 'vehicle.cylinders': 'Hengerek', 'vehicle.power': 'Teljesítmény', 'vehicle.torque': 'Nyomaték', 'vehicle.transmission': 'Sebességváltó', 'vehicle.drivetrain': 'Hajtás', 'vehicle.economy': 'Kombinált fogyasztás', 'vehicle.history': 'SZERVIZELŐZMÉNYEK', 'vehicle.activity': 'Legutóbbi tevékenység', 'vehicle.addRecord': 'Bejegyzés hozzáadása', 'vehicle.records': 'Karbantartási bejegyzések', 'vehicle.notFound': 'A jármű nem található', 'vehicle.return': 'Vissza a garázshoz', 'maintenance.date': 'Dátum', 'maintenance.odometer': 'Futásteljesítmény', 'maintenance.description': 'Elvégzett munka', 'maintenance.category': 'Kategória', 'maintenance.cost': 'Költség', 'maintenance.performedBy': 'Elvégezte', 'maintenance.owner': 'Tulajdonos', 'maintenance.workshop': 'Szerviz', 'maintenance.save': 'Bejegyzés mentése',
	},
}

function readLocale(): Locale {
	if (typeof localStorage === 'undefined') return 'en'
	const saved = localStorage.getItem(STORAGE_KEY)
	return saved === 'sk' || saved === 'hu' ? saved : 'en'
}

export function useI18n() {
	const t = (key: string, values: Record<string, string | number> = {}) => {
		const template = messages[locale.value][key] ?? messages.en[key] ?? key
		return Object.entries(values).reduce((text, [name, value]) => text.replace(`{${name}}`, String(value)), template)
	}
	const setLocale = (next: Locale) => {
		locale.value = next
		localStorage.setItem(STORAGE_KEY, next)
		document.documentElement.lang = next
	}
	return { locale, locales: computed(() => [{ value: 'en' as const, label: 'English' }, { value: 'sk' as const, label: 'Slovenčina' }, { value: 'hu' as const, label: 'Magyar' }]), t, setLocale }
}
